# Generated by Django 4.0.2 on 2022-03-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
                ('cnum', models.CharField(max_length=100)),
                ('eml', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('password', models.CharField(default='website', max_length=100)),
                ('uname', models.CharField(max_length=100)),
            ],
        ),
    ]
